---
output:
  pdf_document: default
  html_document: default
---
# Introducción

<div style="text-align: justify">

La violencia es uno de los componentes principales de la experiencia humana. Se presenta de distintas formas y en distintos niveles; está en la guerra y en los conflictos raciales, así como también en el crimen y las relaciones interpersonales. Es un fenómeno que tiene implicancias en todas las esferas de la vida: causa sufrimiento, humillación y, muchas veces, va aparejada de grandes cambios sociales. En consecuencia, no es sorpresa que haya sido un elemento crucial para la reflexión a lo largo de la historia. Desde los orígenes del pensamiento moderno, la violencia ha sido concebida cómo uno de los principales fenómenos a resolver para avanzar hacia la convivencia pacífica entre los seres humanos. Por ejemplo, desde el contractualismo se concibe la entrega del derecho al uso de la violencia a un soberano como parte del proceso civilizatorio [@Hobbes2002]. Así también, desde la sociología clásica se plantea a la centralización y racionalización de la violencia cómo un elemento constitutivo a la formación de los Estados modernos [@Weber1996]. En la actualidad, la necesidad de lidiar con la violencia para avanzar hacia la convivencia pacífica se traduce en que todas las sociedades democráticas deben enfrentarse al desafío de disminuir los niveles de violencia [@Gerber2017; @Keane2004]. 

<div style="text-align: justify">

La violencia no es un fenómeno que se pueda erradicar en el corto plazo. Más bien, es un fenómeno con el cual se debe coexistir planteando límites para su uso [@Keane2004]. Dicho de otra forma, coexistir con la violencia implica determinar las situaciones en que su uso estaría justificado. Generalmente, se entiende la violencia como el daño físico ejercido de manera intencional [@Bufacchi2005] y su justificación como una argumentación de que el acto violento trae alguna consecuencia que lo compense [@Frazer2020]. Desde la tradición sociológica, se tiene la concepción de que es el Estado quien tiene el monopolio de la violencia física [@Weber1996] y, por ende, son los agentes representantes del Estado quienes tienen el derecho legítimo al uso de la violencia. Cómo su tarea es mantener el orden social, el uso de la violencia les está justificado. Sin embargo, tanto la literatura como los procesos sociopolíticos recientes han mostrado que este no es siempre el caso. Existen una serie de otras situaciones en las que la violencia podría ser justificada por parte de la población.


<div style="text-align: justify">

Que la población justifique la violencia en tiempos de las democracias contemporáneas parece algo paradójico, más aún considerando los esfuerzos a nivel internacional que se han hecho para erradicar la violencia [@WHO2014; @WHO2010; @WHO2009]. No obstante, las movilizaciones masivas del 2019 en Chile hacen pensar que esta no es una idea tan lejana a la realidad. El llamado _estallido social_ fue un proceso caracterizado por violaciones sistemáticas a los derechos humanos por parte de la policía [@Human2019; @ONU2019; @Defensoria2020; @Amnistia2020], así como también por un alza en la cantidad de protesta violenta, en comparación a otro tipo de conflictos en los últimos 10 años en el país [@Joignant2020]. Este evento permite plantear dos reflexiones. Por un lado, pareciese ser que la violencia ejercida por agentes estatales no siempre está justificada. Por otro lado, gran parte de la población consideró a la violencia como una vía de manifestación justificada. De hecho, encuestas recientes muestran que la violencia como forma de protesta tuvo un incremento en sus niveles de justificación, mientras que la justificación a la violencia policial disminuyó considerablemente [@ELSOC2019] (ver Figura \@ref(fig:justintro)). El ascenso en los niveles de justificación de la violencia se torna especialmente relevante si se tiene en consideración que aquellos que justifican la violencia son más tendientes a ejercerla [@Nunes2021] o a condonar el actuar violento de otros miembros de la sociedad [@Kalmoe2014]. La consecuencia de esta relación es una potencial escalada de violencia que amenaza la convivencia pacífica [@Gerber2017]. Ante esta problemática, se abren las interrogantes sobre quiénes y por qué razones las personas justifican la violencia.


```{r justintro, echo=FALSE, message=FALSE, warning=FALSE, fig.cap="Justificación de la Violencia de Carabineros y Manifestantes por año"}

pacman::p_load(tidyverse,sjPlot, sjmisc, sjlabelled, elsoc, ggplot2, ggrepel) # librerias
knitr::opts_chunk$set(warning = FALSE,  # mensaje de warning
                      message = FALSE,  # mensajes/avisos de librerias  
                      cache = FALSE,    # cache de los chunks,usar analisis pesados
                      # out.width = '50%',# largo de imagen en %
                      fig.pos= "H",     # posicion figuras H = HERE
                      echo = FALSE      # incluir chunk en output
)

elsoc::load_elsoc('long')

elsoc_long_2016_2021 <-elsoc_long_2016_2021[!(elsoc_long_2016_2021$ola == 5),]

elsoc_long_2016_2021 %>% 
  filter(tipo_atricion == 1 & muestra == 1 & 
           !f05_03 %in% c(-888, -999) & !f05_04 %in% c(-888, -999) & !f05_07 %in% c(-888, -999)) %>% 
  select(f05_03, f05_04, f05_07, ola, ponderador02, segmento_disenno, estrato_disenno) %>% 
  pivot_longer(cols = c(f05_03, f05_04, f05_07)) %>% 
  prop(value %in% 4:5, by = c(ola, name), na.rm = TRUE) %>% 
  mutate(name = factor(name,
                       levels = c('f05_03', 'f05_04', 'f05_07'),
                       labels = c('Carabineros use la fuerza para\n reprimir manifestación pacífica',
                                  'Carabineros desaloje a la fuerza\na estudiantes de liceo en toma',
                                  'Estudiantes tiren piedras a Carabi-\nneros en marcha por la educación'))) %>%
  sjlabelled::as_label(ola) %>% 
  ggplot(aes(y = prop, x = ola, color = name, group = name,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() + 
  geom_point(size = 1.75) + 
  geom_line() +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, .5)) +
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = 0, end = .7, option = 'viridis') + 
  ggrepel::geom_text_repel(size = 3, nudge_y = .02) +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank()) +
  
    scale_x_continuous(breaks = c(1,2,3,4), labels=c("2016", 
                            "2017", 
                            "2018", 
                            "2019")) +
  ggtitle(NULL,
        subtitle = 'Porcentaje que responde que Muchas veces o Siempre se justifica' ) +
  labs(caption = 'Fuente: COES (2022) Radiografía del Cambio Social: Análisis de Resultados Longitudinales ELSOC 2016-2021. Presentación de Resultados COES. Enero, Santiago de Chile.\nNota: Se consideran observaciones de individuos sin atrición entre olas. N=7.507 (1.513 individuos)')
```


<div style="text-align: justify">

Existen dos maneras principales de abordar la justificación de la violencia, y que son centrales para esta investigación: la violencia por el cambio social y por el control social [@Blumenthal1972]. La violencia por el cambio social es aquella que busca cambiar las jerarquías en la sociedad, en cambio, la violencia por el control social es aquella que busca mantenerlas. En base a esta distinción, la literatura empírica ha ofrecido tres explicaciones sobre por qué los individuos podrían justificar ambos tipos de violencia. La primera explicación proviene de la literatura criminológica [@Thompson2004], dónde se ha generado evidencia sistemática respecto a que quienes pertenecen a ciertos grupos desaventajados (e.g. minorías racionales o bajo estatus) tienden a justificar más la violencia por el cambio social y menos por el control social. La segunda explicación proviene de la literatura psicológica, dónde a través de las teorías de la dominancia social (SDO, por sus siglas en inglés) [@Sidanius1999] y del autoritarismo de derecha (RWA, por sus siglas en inglés) [@Altemeyer1988] se ha encontrado que quienes presentan estas ideologías en mayor grado, suelen justificar más la violencia por el control social y menos por el cambio social. La tercera explicación proviene del marco de los estudios de justicia procesal [@Tyler2006], donde se ha encontrado que quienes perciben que las autoridades son justas en sus tratos tienden a justificar más la violencia por el control social y menos por el cambio social [@Gerber2017a]. Es esta última explicación a la que se la ha puesto más atención en los últimos años.

<div style="text-align: justify">

Los estudios sobre justicia procesal han dado pie al desarrollo de una incipiente agenda de investigación. Tanto estudios internacionales [@Gerber2017b; @Bradford2017], cómo estudios en Chile [@Puga2016; @Gerber2016; @Gerber2017a; @Gerber2017] han generado hallazgos que sustentan la construcción de esta agenda. No obstante, la justicia no es un fenómeno unidimensional, sino que tiene múltiples dimensiones, siendo las más comunes la distributiva y la procesal [@Tornblom2007]. La justicia distributiva refiere a una evaluación normativa de la distribución de recursos (generalmente, ingresos) de una situación [@Jasso2015]. En cambio, la justicia procesal se entiende cómo los juicios respecto a qué tan justo es el trato que ejercen ciertos actores (generalmente, autoridades) a los individuos [@Tyler2003]. Considerando los hallazgos sistemáticos respecto al rol que tiene la justicia procesal en la justificación de la violencia, este trabajo abre la pregunta sobre sí es que otras dimensiones de la justicia podrían contribuir a explicar las dinámicas de la justificación de la violencia, como por ejemplo, la justicia distributiva. Considerando lo anterior, en este estudio propongo integrar a la justicia distributiva cómo una dimensión relevante para explicar las justificaciones de la violencia. En consiguiente, la pregunta que guía el estudio es: ¿Cuál es la relación entre el sentido de injusticia distributiva y las justificaciones de la violencia en contexto de protesta, tanto por el cambio social, como por el control social, en Chile al año 2019?

<div style="text-align: justify">

La justicia distributiva podría contribuir a explicar las dinámicas de la justificación de la violencia por dos razones. Una primera razón es que el sentir injusticia es una fuerza social que motiva el comportamiento humano [@Liebig2016]. Considerando esta característica, en el marco de la sociología de la justicia se han desarrollado modelos teóricos que buscan esquematizar el rol de la injusticia tanto a nivel individual, así como sus consecuencias a nivel agregado [e.g. @Liebig2016]. Bajo este prisma, no es difícil encontrar propuestas que destacan el rol de la injusticia en acciones violentas: desde propuestas clásicas que consideran a la injusticia en la distribución de recursos cómo el factor movilizante de grandes revueltas o revoluciones [e.g. @BarringtonMoore1978; @Gurr1970; @Jasso1980], hasta estudios empíricos más recientes que consideran a la injusticia cómo un generador de emociones que motivan la protesta [e.g. @Agostini2021; @Tausch2011]. No obstante, este planteamiento implica una relación lineal entre sentir injusticia y sucesos violentos, sin considerar el rol de las justificaciones cómo una antesala de las acciones. Considerando que quienes ejercen violencia suelen previamente justificarla [@Nunes2021; @Kalmoe2014], se esperaría que el sentido de injusticia también tenga un efecto en cómo las personas justifican la violencia. Dicho de otra forma, antes de plantear una relación entre injusticia y violencia, es necesario comprender sí las personas consideran que el sentir injusticia es una razón para justificar la violencia.

<div style="text-align: justify">

Una segunda razón es la conceptualización que se ha hecho del sentido de injusticia en la agenda de justicia distributiva. Particularmente, la teoría de las evaluaciones de justicia propone que el sentido de injusticia es resultado de las comparaciones que hacen los individuos entre la distribución real de recompensas y una que consideran justas para una situación de distribución [@Jasso1978; @Jasso1980]. Estas comparaciones pueden ocurrir cuando individuos evalúan situaciones de distribución en las que ellos son los recompensados, así cómo también cuando evalúan la justicia en la distribución para otros individuos [@Jasso2015]. Considerando esto, la injusticia que podría explicar las justificaciones de violencia no nace de la nada, sino que de procesos de comparación social que conllevan ciertas nociones de justicia y percepciones de cómo se distribuyen ciertas recompensas en la sociedad. Dicho de otra forma, la conceptualización del sentido de injusticia que entrega la agenda de justicia distributiva aporta una explicación más detallada respecto a qué implica sentir injusticia, lo que permitiría comprender cómo es que un individuo que siente injusticia podría llegar a justificar la violencia.

<div style="text-align: justify">

El caso de Chile se torna especialmente relevante para estudiar la relación entre el sentido de injusticia y las justificaciones de violencia. Chile es un país caracterizado por la desigualdad económica y social [@PNUD2017]. La lectura que se ha hecho del estallido social es que fue la acumulación de desigualdades estructurales que la población concebía como injustas lo que llevó a las grandes movilizaciones del 2019 [@Somma2020]. Inclusive, años atrás el informe de @PNUD2017 diagnosticaba las diversas desigualdades socioeconómicas que vivía el país, tales como las brechas de ingreso o las diferencias de trato. De esta manera, tiene sentido plantear que, en uno de los países más desiguales de América Latina, los sentimientos de injusticia jugaron un rol importante en que la gente justificara la violencia que caracterizó el estallido social. La intención de este escrito no es explicar las movilizaciones del 2019, sino usarlas como caso paradigmático en donde esta relación podría ser particularmente fuerte.

<div style="text-align: justify">

El argumento central de este estudio es que, posterior al estallido social, el sentido de injusticia en los ingresos llevó a los chilenos a justificar más la violencia por el cambio social, y menos la violencia por el control social. En este caso, me centraré en la violencia en el contexto de protesta, por lo que las situaciones que este estudio abarca tienen que ver con dos actores principales: carabineros y manifestantes. Además de esta hipótesis principal, basándome en la idea de que suelen ser los más desfavorecidos los que sienten la injusticia, analizaré el potencial rol moderador del sentido de injusticia en la relación entre la pertenencia a grupos desaventajados y las justificaciones de violencia en contexto de protesta.

<div style="text-align: justify">

Este trabajo pretende contribuir con tres aportes: dos a la literatura y uno social. El primer aporte consiste en incorporar una dimensión explicativa antes no explorada al estudio de la justificación de la violencia. En detalle, se pretende complementar la construcción de la agenda de justificación de la violencia y justicia procesal a partir del estudio de otra dimensión de la justicia. El segundo aporte corresponde a la contribución con evidencia empírica a los estudios de justicia en sociología. Este aporte se enmarca en la línea teórica que ha planteado el estudio de las consecuencias de la justicia cómo uno de los pilares en la agenda de justicia distributiva [@Jasso2015], así cómo también en los modelos recientes que se han desarrollado para comprender los determinantes y efectos de la justicia [@Liebig2016]. Dicho de otra manera, este trabajo pretende aportar, por un lado, a la agenda de justificación de violencia y, por otro, a la agenda de justicia distributiva. Además de los aportes a la literatura, este estudio ofrece un tercer aporte el cuál consiste en información para la discusión pública respecto al estallido social en Chile. Se pretende que la información y los hallazgos generados en este trabajo sean evidencia para la discusión sobre el estallido social. 

<div style="text-align: justify">

Este escrito tendrá cuatro secciones. Primero, se tratará con más detalle el objeto de estudio, a saber: la justificación de la violencia en contexto de protesta. Segundo, se revisarán los determinantes asociados a la justificación de la violencia según la literatura. Tercero, se revisarán los datos y el método a utilizar para la elaboración de resultados. Cuarto se presentarán los análisis. Por último, se presentan las discusiones y conclusiones de los hallazgos con relación a la literatura existente. Al final de este trabajo el lector tendrá conocimiento de algunas potenciales explicaciones de las justificaciones de violencia posterior al estallido social en Chile.

