---
output:
  pdf_document: default
  html_document: default
---

```{r echo=FALSE}
knitr::opts_chunk$set(out.width="80%", fig.pos = "!ht", out.extra = "")
```

# Antecedentes conceptuales y empíricos

## Violencia, desglosando el concepto

<div style="text-align: justify">

La violencia es, sin duda, uno de los conceptos más complejos en el estudio de la sociedad. Distintos académicos han trabajado a fin de responder lo que se considera una de las grandes preguntas filósoficas: ¿qué es la violencia? Estos esfuerzos han llevado a una amplia producción académica que ha buscado sintetizar esta complejidad [e.g. @Kurt2008; @Heitmeyer2005; @Bufacchi2009a]. El punto de partida de toda esta empresa intelectual es siempre el mismo: la definición de violencia no es solo una, sino que viene en muchos tipos y formas. La violencia puede estar en las micro interacciones o en las grandes estructuras sociales, puede ocurrir en las relaciones de pareja, en el trabajo, en la familia y en la escuela, o en la cultura y las instituciones. Violencia puede ser desde un marido que golpea a su mujer, hasta la represión policial en el contexto de protesta; pueden ser las prácticas coloniales que marginalizan a ciertos grupos minoritarios o las estructuras de injusticia en una sociedad. En síntesis, la violencia abunda, al igual que las tipologías que existen para entenderla. Ante tal complejidad es que un estudio sobre la violencia, especialmente uno de carácter empírico, debe dejar bien establecida qué es la violencia y qué tipo de violencia se está estudiando.

Uno de las distinciones base en la literatura refiere al tipo de enfoque que se adopta al momento de definir la violencia. Es decir, ¿cuál es el criterio que se prioriza al momento de definir si algo es violento o no? Los académicos han coincidido en que la gran mayoría de las definiciones que se pueden encontrar se centran o en el uso de la fuerza física o en la violación de derechos, dando pie a los dos grandes enfoques existentes [@Bufacchi2005]. Por un lado, está el enfoque minimalista, y por otro lado, el enfoque comprehensivo. Cada aproximación cuenta con sus ventajas y desventajas, las que se exponen a continuación.  

El enfoque minimalista comprende la violencia como un acto de fuerza física intencional que causa daño en quien lo recibe. Por ejemplo, un sujeto que golpea a otro hiriendolo intencionalmente. Este es el enfoque más recurrente, tanto en el sentido común, como en la investigación empírica y teórica. Su ventaja recae en qué, dada la estrechez de su definición, hace a la violencia un fenómeno fácilmente delimitable y abordable para la investigación empírica. Además, al incluir la idea de intencionalidad permite una discusión más clara sobre la evaluación moral del acto. Autores como @Keane2004 o @Coady2008 llaman a preservar este tipo de definiciones por su fácil operacionalización. Sin embargo, autores como @Galtung1969 o @Bufacchi2007 argumentan que delimitar la violencia hacia la fuerza física, la intencionalidad y el daño lleva a ignorar una serie de dimensiones de la violencia igualmente importantes, tales como la violencia psicológica, simbólica o estructural.  

Un enfoque más estrecho relacionado a la definición minimalista es el *legitimista*. El enfoque legitimista parte de la base que el criterio definitorio de la violencia es el uso de la fuerza fisica intencional, pero añade la condición de que debe ser ejercida por perpetradores no legítimos para ser considerada violencia. En otras palabras, restringe la definición de violencia hacia actores no estatales. De esta manera, las autoridades legitimas como policías o militares no cometen violencia, sino que hacen uso de la fuerza con tal de mantener el orden social. Esta postura ha sido defendida por autores como @Hook1976, caracterizando una visión conservadora sobre la violencia. Desde este punto de vista, dimensiones como la violencia institucional son de plano equivocadas. Por ende, desde este enfoque la violencia utilizada desde agentes privados es eminentemente peyorativa.  

En contraste al enfoque minimalista, el enfoque comprehensivo pone el foco en la idea de violación. Violar significa la transgresión de un límite o norma [@Bufacchi2005; @Bufacchi2007], siendo la pregunta consiguiente ¿qué es violado? Autores como @Gerd1969 responden definiendo la violencia como la violación de las primeras tres reglas morales: no matar, no causar daño, no deshabilitar. No obstante, la respuesta más común es que un acto de violencia es aquel que viola los derechos más básicos de un individuo, así como el derecho a la vida o a la seguridad etc. [@Copoeru2020]. Autores como @Demirbas2019 han sido más enfáticos en entender la violencia como la violación a los derechos humanos. La ventaja de este enfoque es que logra abarcar las dimensiones que la versión minimalista de la violencia dejaba de lado: la violencia no directamente visible, inserta en la estructura social, las instituciones o la cultura, lo que @Zizek2008 ha llamado violencia objetiva. Esta perspectiva prioriza la visión que tienen las víctimas de injusticias sobre la violencia, ya que son sus derechos los violados. En esa línea, es que @Galtung1969 o @Bourdieu1991 han trabajado en torno a conceptos como violencia estructural o violencia simbolica, respectivamente. La desventaja de esta aproximación es su caracter omniabarcante, autores como @Bufacchi2005 plantean que este enfoque puede llevar a concebir la violencia como todo lo moralmente incorrecto y privándolo de su utilidad conceptual. La violencia pasa a ser un detector de injusticas más que un concepto con utilidad para la reflexión teórica y la investigación empírica [@Arostegui1994].  

En síntesis, los componentes principales del enfoque minimalista son la fuerza, la intencionalidad y el daño, siendo una definición que se centra en el acto directo del perpetrador. En cambio, el enfoque comprehensivo se centra en la violación de los limites o las normas, usualmente de derechos, poniendo el foco en la vivencia de la víctima. Dada su claridad conceptual, y a falta de una base empírica sobre qué es lo que entienden los chilenos por violencia, es que este trabajo se basa en una definición minimalista de la violencia. Sin embargo aun queda por conceptualizar cuál es la situación en la que se enmarca el acto de violencia, cuestión que se especificará posterior a entender la definición base del objeto de estudio de este trabajo: la justificación de la violencia.

## Justificación de la violencia

<div style="text-align: justify">

La justificación de la violencia parte de la base que hay algo en estos actos que los hace desvincularse de una acción meramente arbitraria [@Basaure2020]. Generalmente, ese algo es que las consecuencias del acto traen consigo algún bien [@Frazer2019]. Es decir, quienes justifican la violencia son aquellas personas que consideran que las consecuencias generadas por el acto violento traerán un bien que compense el daño efectuado durante el proceso. El conocido dicho _el fin justifica los medios_ representa bastante bien esta postura. Enfocar la justificación de la violencia a partir de sus consecuencias significa concebir la violencia como un acto instrumental [@Blumenthal1972; @Arendt2005], o sea, que cuenta con un fin que orienta su actuar. Por ende, la discusión sobre la justificación de la violencia gira en torno a cuáles son esos fines por los cuales las personas estarían dispuestas a utilizar medios violentos para conseguirlo.

El campo de estudios sobre la justificación de la violencia se puede dividir en dos grandes áreas disciplinares. Primero están los estudios en teoría política, filosofía y ética, los cuales han contribuido con reflexiones desde un punto de vista normativo. Estos trabajos giran en torno a una gran pregunta ¿puede la violencia ser justificada? Generalmente esta pregunta se sitúa en el campo de la violencia política, indagando en las condiciones, los argumentos y los principios por los cuáles se podría argumentar que la violencia revolucionaria o la violencia en contexto de protesta son moralmente defendibles [@Demirbas2019; @Frazer2019; @Gerd1969; @Hills2011; @Keane2004; @Magil2008; @Nielsen1981; @Wells1970]. Las discusiones en torno al argumento *ticking bomb* [ver @APT2007; @Bufacchi2006] o al asesinato de Hitler [ver @Dean2005; @Frazer2019] son algunos ejemplos de estas situaciones. Si bien no es la prioridad de este trabajo el enfoque normativo, si sienta una base importante para su estudio empírico, especialmente considerando que muchos estudios empiricos sobre violencia han caído en confusiones conceptuales por no considerar el trabajo teórico en el área [@Bufacchi2007]. Segundo, está el estudio empirico sobre los factores que llevan a las personas a justificarla violencia. Será en esta segunda área temática donde este trabajo se enmarca, y en donde sentará sus aportes. Dado este enmarque, es que un breve recorrido por lo que han sido las principales agendas de investigación se presenta a continuación.

El primer estudio empírico que trata las justificaciones de violencia desde un enfoque instrumental es @Blumenthal1972. Este estudio sienta las bases al conceptualizar la violencia de acuerdo a dos fines contrapuestos: por el control social y por el cambio social. A grandes rasgos, la violencia por el control social son aquellas acciones orientadas a la mantención de las jerarquías en la sociedad y la violencia por el cambio social las acciones que buscan generar un cambio en esas jerarquías. En base a esta distinción, los enfoques se han diversificado. Por un lado, la violencia por el control social puede ser ejercida por agentes privados o públicos. Cuando se trata de agentes privados, el estudio se ha centrado en actitudes hacia el castigo y la justificación de linchamientos por parte de la ciudadanía [e.g. @Gerber2012; @Gerber2016; @Puga2016]. Cuando se trata de agentes públicos, se ha acuñado el concepto de violencia institucional, entendida como las medidas que toma el Estado para reprimir principios de libertad y justicia con el fin de mantener el orden social [@Nielsen1981]. Ejemplos de este tipo de violencia son los castigos penales o la violencia policial [@Puga2016]. Por otro lado, la violencia por el cambio social puede ser a nivel revolucionario, o más bien tácticas de protesta que buscan generar cambios dentro de la sociedad [@Nielsen1981]. La violencia revolucionaria se refiere al uso de la violencia para lograr cambios estructurales a nivel político, social y económico [ver @Nielsen1977; @Sune2010; @Edyvane2020]. La violencia dentro del Estado para el cambio social apunta a la generación de cambios que no buscan la transformación total en el corto plazo. Este trabajo busca estudiar las justificaciones de violencia por el control social ejercida por agentes públicos (carabineros) y las justificaciones de violencia por el cambio social a nivel de tácticas de protesta (manifestantes).

Si bien esta es una distinción clave en los estudios contemporaneos de la justificación de la violencia, no fue retomada cómo tal hasta los 2000 por autores cómo @Jackson2013 o @Gerber2016. Es más, gran parte de los aportes provienen de la literatura criminológica en los Estados Unidos bajo el estudio de conceptos como _actitudes o apoyo hacia el uso de la fuerza por parte de la policía_, y no de violencia como tal. En esta línea muchos artículos se centraron en los factores que lleva a la gente a apoyar uso de la fuerza policial [@Gamson1970; @Arthur1993; @Arthur1994; @Thompson2004; @Perkins2006; @Johnson2009] o también en el desarrollo de escalas para la medición de este concepto [@Barkan1998; @Jefferis2011]. La aplicación del concepto de violencia es más reciente, donde académicos, especialmente desde la psicología, han introducido dos marcos teóricos al estudio de la justificación de la violencia. Por un lado, los trabajos de @Henry2005 y  @Gerber2017b han aplicado la teoría de la dominancia social [@Sidanius1999] y la teoría del autoritarismo de derecha [@Altemeyer1988]. Estas teorías parten del supuesto que la vida en sociedad está conformada por grupos con atribuciones de personalidad diferenciadas, donde ciertos grupos buscan  dominar a otros. A raíz de esta aplicación es que utiliza el concepto de _violencia intergupal_. Por otro lado, el trabajo de @Jackson2013 fue el primero en aplicar el marco de la justicia procesal, siendo las justificaciones de la violencia una actitud derivada de la legitimidad atribuida a los agentes de orden y de las nociones de procesos justos. Esta linea es la que se ha potenciado recientemente con los trabajos de @Gerber2017a, @Gerber2017b y @Bradford2017. Tanto la aplicación desde las teorías de la dominancia social como las de la justicia procesal han trabajado bajo la distinción de violencia por el cambio social y violencia por el control social.

El trabajo de @Gerber2017a ha sido particularmente importante al plantear una definición más detallada de ambos tipos de violencia. Por un lado, se entiende la violencia por el control social como “aquellas situaciones en donde la violencia es ejercida por grupos dominantes-mayoritarios por sobre grupos subordinados-minoritarios o cuando el objetivo de la violencia es el de reducir el potencial cambio en las estructuras normativas o jerárquicas de la sociedad” [@Gerber2017a , pp. 3-4, traducción mía]. Por otro lado, la violencia por el cambio scial corresponde a “aquellas situaciones en donde la violencia es ejercida por grupos subordinados-minoritarios por sobre grupos dominantes-mayoritarios o cuando el objetivo de la violencia es crear cambios en la estructura jerárquica o normativa de la sociedad [@Gerber2017a, p.4, traducción mía]. Estas definiciones orientan el presente trabajo.

## Determinantes de la justificación de la violencia

<div style="text-align: justify">

El diagnostico base de esta revisión de literatura es que no existe una agenda de investigación en donde la justificación de la violencia sea el concepto central, sino que a raíz del estudio de distintos conceptos través de distintas disciplinas se ha armado un cumulo de evidencia empírica que contribuye a la discusión en el área. Cómo se ha señalado, son tres las aproximaciones. Primero, están los estudios criminológicos que han trabajado las actitudes al uso de la fuerza por parte de la policía. En general, estos estudios han encontrado evidencia a favor de las teorías del conflicto [@Chambliss1995; @Quinney1971; @Turk1969], donde se concibe que la policía está al servicio de los grupos con mayor estatus en la sociedad. Por ende, un primer gran hallazgo es el rol que tiene el estatus o el caracter de minoría-mayoría de las personas. Personas de más bajos estatus o pertenecientes a grupos minoritarios tienden a apoyar menos el uso de la fuerza por parte de la policía. En segundo lugar, la aplicación de las teorías de la dominancia social [@Sidanius1999] y el autoritarismo de derecha [@Altemeyer1988] han relevado el rol que tienen los valores autoritarios en la justificación de la violencia, donde personas con más valores autoritarios son más propoensos a justificar la violencia por el orden social. En tercer lugar, los estudios planteados desde la teoría de la justicia procesal [@Tyler2006] han relevado el efecto que tienen las nociones de que la policia actúa de manera justa en los procedimientos asociados a su cargo en la legitimidad policial. El que las personas conciban que la policía es legitima, lleva a que estén más de acuerdo con el uso de violencia por parte de ella. En conjunto a estos tres grandes hallazgos, es que se ha demostrado el efecto de otro tipo de variables, como las caracteristicas sociodemográficas [@Gamson1970; @Blumenthal1972; @Arthur1994; @Thompson2004; @Gerber2017], la identificación con el grupo victimario o victima [@Bradford2017; @Gerber2017a] o las nociones de justicia retributiva [@Blumenthal1972; @Puga2016].

### Estatus y minorías

<div style="text-align: justify">

El mayor hallazgo en la literatura sobre el uso de fuerza por parte de la policía ha sido que los grupos de menor estatus y las minorías (raciales y de genero) son quienes desaprueban más la violencia policial. Por ejemplo, @Gamson1970 halló que los ciudadanos estadounidenses negros, los pobres y los financieramente insatisfechos son quienes tienden a desaprobar la violencia policial, en contraste a aquellos estadounidenses blancos, ricos y financietamente satisfechos. @Arthur1994 contribuyó en esta linea encontrando que los estadounidenses blancos, con mayores niveles de educación y más ricos son quienes más apoyan la violencia por parte de los policías. @Weitzer2002 también halló que las personas negras e hispanas justificaban menos la violencia ejercida por la policía. Los trabajos de @Blumenthal1972, @Thompson2004 y @Johnson2009 han generado evidencia del mismo tipo para la raza y para el sexo. A fin de cuentas, estos hallazgos han robustecido la idea de que la relación ente las actitudes a la policia y caracteristicas asociadas al estatus se puede enmarcar en las teorías del conflicto [@Chambliss1995; @Quinney1971; @Turk1969], donde la policía es vista como un agente que perpetúa las desigualdades de estatus dentro de la sociedad. Todos los estudios que han contribuido a evidenciar el rol del estatus en relación a las actitudes hacia la violencia se han centrado, según la distinción que adopta este trabajo, en la violencia por el control social. Sin embargo, no es difícil imaginar que aquellas personas en el eslabón más bajo de las jerarquías sociales consideren que tales jerarquías deben ser minimizadas o abolidas, lo que las llevaría a justificar más la violencia por el cambio social. Las dos primer hipotesis de este trabajo son las siguientes:

> $H_1:$ Personas de menores estatus tenderán a justificar menos la violencia por el control social  
> $H_2:$ Personas de menores estatus tenderán a justificar más la violencia por el cambio social.  

### Valores autoritarios

<div style="text-align: justify">

La teoría de la dominancia social (SDO) argumenta que los conflictos intergrupales (e.g clasismo) provienen de predisposiciones básicas del ser humano a formar sistemas sociales organizativos que mantengan las jerarquías entre grupos [@Sidanius1999]. La teoría de del autoritarismo de derecha (RWA) propone que existen personalidades caraterizadas por una sumisión y lealtad ciega a la autoridad, una agresividad hacia quienes se desvían de las normas sociales planteadas por las autoridades y una alta adherencia a esas normas [@Altemeyer1988]. El primer trabajo en introducir estos conceptos al estudio de la aprobación de la violencia fue @Henry2005 (aunque no basado en la distinción control/camio social). A partir de una muestra de estadounidenses y otra de libaneses, los autores evidencian que los estadounidenses que puntuaban alto en SDO tendían a justificar más la violencia contra el Medio Oriente, y los libaneses que puntuaban menos en SDO justifican más la violencia contra Occidente. Estos resultados son interpretados en tanto 1) la violencia desde los libaneses es vista como de contradominio y 2) las actitudes dependen del tipo de conflicto y los actores involucrados. Otro trabajo mostró que gente que puntuaba alto en SDO tendía a percibir menos que la policía hacía uso indebido de la fuerza en situaciones extremas [@Perkins2006]. Más recientemente @Gerber2017b han mostrado que las personas que puntúan alto en SDO y RWA tienden a justificar más el uso de la fuerza excesiva por parte de la policía. Dado que los datos a utilizar en el presente trabajo no cuentan con las escalas para estos constructos, estos posibles predictores quedan presentados solo a modo de antecedentes.


### Justicia procesal

<div style="text-align: justify">

La forma más básica de definir las experiencias relacionadas a la justicia procesal es qué tan justamente consideran las personas que son tratadas [@Gonzales2007; @Vermunt2016]. La hipotesis central de este marco es que la forma en la que se toman las decisiones sobre la distribución de recursos influye en las reacciones de la gente sobre esas decisiones [@Vermunt2016]. Un argumento que está en el núcleo de esta teoría es que la legitimidad de la policía lleva a la aprobación de sus acciones. La policía está siendo constantemente evaluada en terminos procesales, lo que le da o quita legitimidad [@Bradford2017]. El trabajo de @Jackson2013 fue el primero en plantear la justificación de la violencia como una posible salida de las experiencias de justicia procesal y la legitimidad de autoridades. En este trabajo se evidencia que a mayor justicia procesal experimentada por las personas, la policía es más legitimada lo que lleva a desaprobar la violencia privada (linchamientos y protestas). En esta linea, @Maguire2016 ha encontrado que experiencias de injusticia procesal llevan a justificar más la violencia en contra de los policías. En el contexto chileno y en el marco del conficto Estado-pueblo Mapuche, @Gerber2017 encuentra que mayores percepciones de justicia procesal están asociadas a mayor justificación de la violencia por el control social, y menos por el cambio social. En esta relación, la legitimidad otorgada a la policía hace de mediador. También, los resultados de @Bradford2017 robustecen el planteamiento de que gente que legitima a la policía aprueba la violencia policial. Dado estos antecedentes, es que se plantean las siguientes hipotesis:

> $H_3:$ Personas que experimenten menor justicia procesal tenderán a justificar menos la violencia por el control social  
> $H_4:$ Personas que experimenten menor justicia procesal tenderán a justificar más la violencia por el cambio social  


### Otros predictores

<div style="text-align: justify">

Han habido otras explicaciones con evidencia a su favor para la justificación de la violencia, especialmente por el control social. Una de ellas ha sido el rol del nivel educacional, que si bien en algunos trabajos ha funcionado como variable de estatus, en otros se ha encontrado la tendencia contraria: personas más educadas desaprueban más la violencia policial [@Gamson1970; @Thomas1977]. Esto se suele explicar a raíz de que la gente educada está más enterada de las desigualdades de estatus en la sociedad. La investigación hasta los tiempos de @Thompson2004 mostraba ser poco concluyente con variables sociodemográficas, sin embargo, trabajos con datos actuales han hallado que las personas de derecha tienden a justificar más la violencia policial y las personas de izquierda más la violencia por el cambio social [@Puga2016; @Gerber2017]; así también, personas de clase media y alta justifican más la violencia por el control social y no por el cambio social [@Gerber2017], lo que contribuye desde datos de Chile a la teoría del conflicto. Un hallazgo importante ha sido la identificación del grupo y los valores relacionados a la justicia retributiva. Respecto al primero, @Blumenthal1972 encontró que quienes se identificaban con la policía, tendían a justificar más su actuar. El trabajo de @Gerber2017b también contribuyó al evidenciar que la identificación con el grupo en desventaja (en este caso Mpuche) tendía a moderar el efecto de la justicia procesal en las justificaciones de violencia. Más recientemente de @Bradford2017 robusteció la idea de que sentir una alineación normativa con la policía llevaba a justificar su actuar. En el caso de la justicia retributiva, en uno de los primeros estudios sobre justificación de la violencia se encontró que, entre grupos minoritarios, a mayor justicia retributiva mayor justificación de la violencia por el cambio, y entre encuestados con respuestas consistentes, a mayor justicia retributiva mayor justificación de la violencia por el control social. Un estudio de @Puga2016 también encontró que gente que estaba más motivada a "poner al delincuente donde corresponde" tendía a justificar más la violencia por el control social. Otro hallazgo interesante que se discutirá después es que la concepciones sobre qué es lo que es un acto violento llevaba a justificar más un tipo de violencia. Por ejemplo, quienes creían que tácticas disruptivas de protesta eran violentas, justificaban más la violencia policial [@Blumenthal1972].


### Violencia y justicia

<div style="text-align: justify">

La propuesta de este trabajo surge de la relación que existe entre la justicia y la violencia. Sin embargo, al igual que la violencia, la justicia es un concepto complejo, haciendo necesario exponer claramente qué significa y cómo se aborda su estudio. Primero, la justicia es un estado de convivencia ideal. @Liebig2016 [p.38] señalan que un estado de justicia comprende tres componentes: 1) igualdad de trato (las personas deben ser tratadas igualitariamente independiente de sus características individuales); 2) imparcialidad (las situaciones de conflicto de intereses deben resolverse a partir de reglas que impliquen un punto de vista imparcial); y 3) consideración de reclamos legítimos, (los individuos deben ser tratados de acuerdo con lo que merecen). En segundo lugar, la justicia es un fenómeno dinámico. Tres afirmaciones sobre la justicia ayudan a entender esta noción: 1) la justicia es un valor social, en tanto describe las formas deseadas de distribución de recursos en una sociedad; 2) la justicia está determinada socialmente, porque las concepciones de lo justo dependen de las estructuras y procesos sociales; y 3) la justicia es una fuerza social, porque afecta las estructuras y los procesos sociales [@Liebig2016, p.38]. Bajo la idea de la justicia como una fuerza social es que se puede analizar su relación con la violencia.

En el campo de la teoría política y la filosofía se ha documentado a la justicia como una de las razones más importantes para justificar la violencia [i.e. @Runkle1976; @Dean2005; @Magil2008; @Galtung1969; @Nielsen1981; @Bufacchi2007; @Wells1970; @Stateva2009; @Frazer2019].En el área de teoría política, autores clásicos como Honderich, Sorel y Locke argumentaron a favor de esta relación. @Honderich2014 señaló que la violencia es un medio justificable cuando se utilizada para alcanzar un estado de igualdad. @Sorel1999 argumentó que la violencia permite recobrar la identidad arrebatada ante las injusticias vividas. Locke [en @Frazer2020] señaló que la violencia es justificable cuando un gobernante se convierte en agresor y genera un estado de injusticia entre sus habitantes. Otros autores en el campo de la filosofía también han argumentado a favor de esta relación. Para @Wells1970 la existencia de un estado de injusticia que causa sufrimiento en quienes lo viven es la razón número uno para la justificación de la violencia. @Reitan2002 señala que, dentro de una situación de violencia interpersonal, la primera condición para justificar una respuesta violenta es que la agresión del perpetrador sea injusta. @Magil2008 argumenta que cuando las mayorías se comporten injustamente con las minorías, la violencia puede ayudar a rectificar la situación. @Nielsen1981 señala que, ante detenciones policiales injustas, la resistencia violenta es justificable. Benjamin [en @Stateva2009] argumenta que la violencia es justa si es que está del lado de los oprimidos. Ante esta relación tan estrecha entre la violencia y la justicia, @Bufacchi2007 propone que la violencia es el punto de partida para reflexionar la justicia, ya que se basan en el mismo mecanismo: la humillación del oprimido por parte de las mayorías. La idea principal que se puede rescatar de las propuestas de estos autores es la siguiente: experimentar ciertos estados de injusticia hace a la violencia un medio jutificable para cambiar ese estado.

El planteamiento de que experimentar ciertos estados de injusticia llevaría a justificar la violencia para revertirlos hace preguntarse ¿qué tipos de injusticia se están viviendo? Generalmente los estudios de justicia se dividen en cuatro grandes formas: justicia restaurativa, justicia retributiva, justicia procesal y justicia distributiva. Tanto la justicia restaurativa, como la justicia retributiva se entienden como una forma de dar respuesta a la ruptura de leyes dentro de una sociedad. La gran diferencia es que la primera se centra en la restauración de relaciones justas entre victima, perpretador y comunidad [@Cohen2016], en cambio, la segunda se centra en los castigos apropiados para quienes rompen las leyes [@Wenzel2016]. Por otro lado, tanto la justicia procesal como la justicia distributiva se centran en la distribución de recursos en la sociedad, sin embargo, la justicia procesal estudia qué tan justas son las formas en las que se toman las decisiones sobre esos recursos [@Vermunt2016], y la justicia distributiva estudia que tan justa la distribución de recursos como tal [@Jasso2016]. Hasta ahora, la revisión de antecedentes ha dejado en evidencia los trabajos sobre la justicia procesal, donde gente que experimenta injusticia en esta área tendería a justificar más la violencia por el cambio social [@Gerber2017b], asi como los hallazgos relacionados a la justicia retributiva, donde gente que adhiere más a valores retributivos justifican más la violencia por el orden social. Las otras dos dimensiones de la justicia y su relación a la violencia han quedado inexploradas.

La justicia distributiva es una dimensión importante de estudio para las justificaciones de violencia dada la fuerza moral y socioeconductual que tienen las experiencias de injusticia distributiva [@Jasso2015]. Cómo se señaló, la justicia distributiva se pregunta por la justicia relacionada a la distribución de recursos en la sociedad. Generalmente, se divide en dos dimensiones. La primera es la justicia de principios, que refiere a los principios o reglas por los cuales la distribución de recursos son hechas. La segunda es la la justicia en las recompensas, que refiere a las concepciones que tengan los individuos sobre la asignación de recursos: "es justo que X obtenga Y" [@Castillo2009]. Por el lado de la justicia de recompensas, existen distintas teorías que buscan explicar la recompensa justa según las consideraciones de personas con características especificas [@Castillo2011], como la teoría de la equidad [@Adams1963; @Homans1961], la de la deprivación relativa [@Runciman1966], la del valor estatus [@Berger1989] y la teoría de la evaluación de justicia [@Jasso1980]. Esta última teoría propone una forma de medición especifica para las experiencias de injusticia, de la cuál se han derivado cuatro grandes preguntas orientativas para la investigación: 1) ¿Cuáles son las recompensas reales?, 2) ¿Cuáles son las recompensas consideradas justas, 3) ¿Cuál es la brecha entre lo real y lo justo? y 4) ¿Cuáles son las consecuencias de la brecha entre lo real y lo justo? Según @Jasso2015 la evaluación de justicia sería capaz de predecir una amplia gama de comportamientos sociales, ya que cuenta con una fuerza moral y socioconductual. Una de las formas más recurrentes de aplicar la evaluación de justicia es para la distribución de ingresos para distintas ocupaciones. La evaluación de justicia se construye a partir de las dos preguntas anteriores: ¿cuáles son la ditrbicuión real de ingresos que percibe la gente y cuál es la que considera justa? En el caso de las _International Social Survey Program_ (ISSP) y la _International Social Justice Project_ (ISJP) que son las encuesta que han dado pie al trabajo en esta área, es que se hace la pregunta para los extremos ocupacionales (obrero no calificado y gerente de una empresa). Una forma de contar con un indicador que logre representar estas experiencias de injusticia distributiva es la brecha de justicia salarial, propuesta por @Verwiebe2000.

Dada la fuerza moral y socioconductual por la que se caracteriza la experiencia de injusticia, el componente moral en la que se basa la justificación de la violencia y el hallazgo sobre que son los grupos de menores estatus quienes desaprueban más la violencia por el control social, es que aquí se propone que esta relación entre estatus y justificación de la violencia podría estar mediada por las experiencias de justicia de las personas, en tanto vivir injusticias en la distribución de recursos modifica los limites morales de las personas, llevando a que vean la violencia como una opción justificable en mayor cantidad de situaciones. De aquí es que se plantean las siguientes hipótesis:

> $H_5:$ Personas de menor estatus justifican menos la violencia por el control social porque experimentan mayores niveles de injusticia en la distribución de ingresos  
> $H_6:$ Personas de menor estatus justifican más la violencia por el cambio social porque experimentan mayores niveles de injusticia en la distribución de ingresos  

Este planteamiento también lleva a proponer los efectos directos:

> $H_7:$ Personas que experimenten mayores niveles de injusticia con respecto a la distribución de ingresos justificarán menos la violencia por el control  
> $H_8:$ Personas que experimenten mayores niveles de injusticia con respecto a la distribución de ingresos justificarán más la violencia por el cambio social  

Si bien este planteamiento es una propuesta nueva en los estudios de justificación de la violencia, sí se podría hallar un respaldo más concreto en la literatura sobre desigualdad económica y violencia política [ver @Ostby2013 para revisión]. En esta área, teorías como la deprivación relativa de @Gurr1970 plantea que la violencia aumenta cuando los ciudadanos viven una situación demasiado lejana a la deseada. En otras palabras, las desigualdades económicas tienen un impacto en la existencia de violencia dentro de las sociedades. Recientemente, @Rustad2016 ha profundizado en esta relación trabajando con variables a nivel subjetivo, es decir, percepciones de desigualdad y actitudes hacia la violencia. Los resultados de @Rustad2016 muestran que las personas que se perciben a sí mismas como desfavorecidas, tienden a apoyar la violencia para generar cambios. Así, desde la literatura de desigualdad y violencia política, se abren las puertas para pensar la justificación de la violencia desde la justicia distributiva.

