# Preguntas y objetivos de investigación

La pregunta que orienta la presente investigación es la siguiente:

> ¿Cuál es la relación entre el sentido de (in)justicia y las justificaciones de la violencia en contexto de protesta, tanto por el cambio social, como por el control social, en Chile al año 2019?

El objetivo general subsecuente es:

> **Determinar** la relación entre el sentido de (in)justicia y las justificaciones de la violencia en contexto de protesta, tanto por el cambio social, como por el control social, en Chile al año 2019

Los objetivos específicos que permitirán dar una respuesta a la pregunta de investigación son los siguientes:

- **Explicar** la relación entre la brecha de ingresos justa y las justificaciones de violencia en contexto de protesta, tanto por el cambio social, como por el control social.

- **Explicar** la relación entre las percepciones del trato justo y las justificaciones de violencia en contexto de protesta, tanto por el cambio social, como por el control social.

- **Explorar** el rol mediador del estatus en la relación entre el sentido de (in)justicia y las justificaciones de violencia en contexto de protesta, tanto por el cambio, como por el control social.

Las hipótesis girarán en torno a los tres objetivos especificos, y se listarán de manera progresiva a medida que se vaya construyendo el argumento en la sección de antecedentes.
