# Discusión y Conclusiones

<div style="text-align: justify">

La pregunta sobre qué lleva a las personas a justificar la violencia es una interrogante que ocupa a filósofos y científicos sociales hace décadas. En la literatura empírica se han ofrecido tres explicaciones. La primera es que quienes pertenecen a grupos desaventajados tienden a justificar actos violentos que buscan generar algún cambio en las estructuras jerárquicas de la sociedad. La segunda es que quienes poseen ideologías más cercanas al autoritarismo o a la dominancia social, tienden a justificar más la violencia que mantiene el _status quo_. La tercera es que quienes perciben que son tratados de manera injusta, legitiman menos a las autoridades y, por ende, justifican menos la violencia que estas ejerzan. Esta última explicación es la que ha recibido más desarrollo en el último tiempo, relevando el rol que tiene sentir injusticia en el trato en la justificación de la violencia. Sin embargo, en el presente estudio se ha partido de la premisa que la justicia no es un concepto unidimensional, sino uno multidimensional. A raíz de ello, se ha propuesto integrar a la justicia distributiva como una dimensión relevante para explicar las dinámicas de la justificación de la violencia. La pregunta que ha guiado el estudio es: ¿Cuál es la relación entre el sentido de injusticia distributiva y la justificación de la violencia?

<div style="text-align: justify">

A fin de responder la pregunta, se han puesto a prueba dos grandes hipótesis. La primera es que el sentido de injusticia tiene un efecto directo en la justificación de la violencia, donde quienes evalúan más injusticia en la distribución de ingresos (H1a) justifican más la violencia por el cambio social y quienes evalúan menos injusticia en la distribución de ingresos, justifican más la violencia por el control social (H1b). La segunda es que el sentido de injusticia también posee un efecto moderador, es decir, cuando individuos que pertenecen a grupos desaventajados evalúan más injusticia en la distribución de ingresos, justifican más la violencia por el cambio social (H2a) y menos por el control social (H2b). Los resultados de este estudio entregan evidencia para sostener la existencia de un efecto directo del sentido de injusticia (H1a y H1b) y evidencia contraria para el efecto moderador del sentido de injusticia (H2a y H2b).


## Aportes Generales

<div style="text-align: justify">

Los resultados del presente estudio contribuyen a dos literaturas distintas. Por un lado, entregan evidencia para establecer a la justicia distributiva como una dimensión explicativa en los estudios de justificación de la violencia. Es decir, además de la pertenencia a grupos desaventajados, la ideología y la percepción de trato justo, la forma en cómo los individuos evalúan la distribución de ingresos para ciertos actores también es una potencial razón que utilizarían las personas para justificar acciones violentas en contexto de protesta. Considerando el emergente desarrollo de una agenda de investigación que se ha enfocado en estudiar la relación entre la percepción de justicia en el trato y la justificación de la violencia intergrupal [@Gerber2021; @Gerber2017a; @Gerber2021a], los hallazgos del presente estudio sientan una base para comenzar a estudiar _la otra cara de la moneda_, esto es, la justicia distributiva. Dicho de otro modo, los hallazgos de este trabajo sirven de puntapié inicial para la apertura de una nueva línea de investigación dentro de la agenda sobre justicia en el trato y justificación de la violencia, una línea de investigación donde se conciba a la justicia como un fenómeno multidimensional y la justicia distributiva como una posible dimensión explicativa. 

<div style="text-align: justify">

Por otro lado, los hallazgos del presente estudio también contribuyen a la literatura de justicia distributiva, al incorporar a la justificación de la violencia dentro de las posibles consecuencias de evaluar injusticia en la distribución de ingresos. Dentro de esta área de estudios, se ha planteado la pregunta por las consecuencias de la injusticia como uno de los pilares que guía el desarrollo de la agenda. No obstante, hasta ahora los estudios sobre las consecuencias de la injusticia son comparativamente menores que estudios sobre otras aristas del fenómeno. En consiguiente, los hallazgos de este trabajo entregan evidencia para sostener que la justificación de la violencia es otro de los fenómenos que se ven afectados por el sentir injusticia. Considerando los nuevos desarrollos en la agenda de justicia distributiva [@Adriaans2020; @Castillo2018], esta evidencia abre la posibilidad al desarrollo de estudios que profundicen en esta relación utilizando otros constructos de injusticia, por ejemplo, la justicia distributiva en el ámbito educacional, de pensiones y otros similares que han emergido recientemente.

<div style="text-align: justify">

En suma, ante dos agendas de investigación con avances prometedores en las últimas décadas, los hallazgos de esta investigación invitan a seguir, por un lado, una línea de investigación que amplíe la relación entre la justicia y la justificación de la violencia, incorporando a la justicia distributiva como un ámbito explicativo. Y, por otro lado, invitan a profundizar la justificación de la violencia como una consecuencia de la injusticia, a través del estudio de otras aristas de la justicia distributiva.


## Aportes Específicos

<div style="text-align: justify">

Además de los aportes generales, los hallazgos de esta investigación permiten discutir aportes específicos a la literatura. En esta investigación se han estudiado dos situaciones de justificación de la violencia. Una donde la violencia se ejerce desde manifestantes hacia carabineros denominada, según la literatura, violencia por el cambio social y otra donde la violencia se ejerce desde carabineros hacia manifestantes, denominada como violencia por el control social. Para ambas situaciones, se indagó en el efecto que tenía el sentido de injusticia, utilizando tres indicadores: la evaluación de la distribución de ingresos del entrevistado, la de un gerente de una gran empresa y la de un obrero no calificado. Según los resultados de este estudio, los efectos de cada indicador varían según la situación de violencia que se justifica y las variables de control que se consideran. Por ende, los hallazgos invitan a discutir estas diferencias, las cuales pueden dar luces al estudio de la relación entre la injusticia distributiva y la justificación de la violencia. 

### Sentido de Injusticia en los Gerentes y Violencia por el Cambio Social (H1a)

<div style="text-align: justify">

En lo que respecta a la violencia por el cambio social, las únicas evaluaciones de justicia que resultaron significativas fueron las de la figura del gerente de una gran empresa. Este hallazgo implica que, independiente de la pertenencia a grupos desaventajados, la ideología y las percepciones de justicia en el trato, quienes consideran que los gerentes están injustamente sobre recompensados justifican más la violencia por el cambio social. El hecho de que este indicador haya resultado significativo y no otro sugiere que cuando la injusticia distributiva figura como una razón para justificar la violencia por cambios sociales, los individuos no observan hacia la situación de los potencialmente más desfavorecidos, sino que a la situación de los más poderosos en la sociedad. Considerando que también se puso a prueba el efecto del sentido de injusticia en los ingresos del entrevistado y de un obrero, los resultados invitan a reflexionar que lo que motiva a justificar la violencia por cambios en la sociedad no es la situación de injusticia de los más desfavorecidos, ni tampoco la injusticia en la situación propia, sino que es la injusticia que emerge al evaluar la situación de las figuras con más poder en la sociedad.

<div style="text-align: justify">

Este hallazgo específico se puede comprender mejor tomando en consideración el contexto del país en el que se efectúa el estudio. Considerando que los datos fueron recopilados en los meses posteriores al estallido social, se podría argumentar que los resultados encarnan gran parte de lo que fue el detonante de las protestas del 2019: un sentimiento de descontento generalizado respecto a la situación de las élites del país. Dentro de la opinión pública del 2019, circulaba la lectura que ciertos discursos o acciones de parte de la clase política y económica actuaron cómo antecedentes y gatillantes de las movilizaciones. Por ejemplo, las frases del ministro Felipe Larraín sobre el precio de las flores, las del ministro Juan Andrés Fontaine sobre los horarios del metro o el caso del presidente de Gasco sobre la propiedad de las playas [@Jimenez2020; @Claro2019; @Tapia2020]. Considerando esta lectura, es que se puede insertar el hallazgo sobre el efecto del sentido de injusticia del gerente dentro de una interpretación más general, donde es la injusticia que se genera al evaluar la situación de *los de arriba* la que podría actuar como una razón para que los chilenos justifiquen tácticas violentas para generar cambios en esas situaciones. 

### Sentido de Injusticia en los Obreros y Violencia por el Control Social (H1b)

<div style="text-align: justify">

El segundo hallazgo específico a discutir es el efecto del sentido de injusticia del obrero en la justificación de la violencia por el control social. Los resultados de este estudio mostraron que, en el caso de la justificación de la violencia por el control social, el único indicador que resultó significativo fue la evaluación de injusticia en la distribución de ingresos de los obreros, donde a menor injusticia se evaluaba, más se justificaba que carabineros usarán la violencia como forma de controlar protestas. Considerando el contexto de Chile post-estallido social, este hallazgo sugiere que una de las razones para justificar el uso de tácticas represivas de parte de carabineros es evaluar que la situación de los más desfavorecidos es justa. Si se lleva este hallazgo a una interpretación más general, se podría argumentar que quienes justifican la violencia de carabineros basados en sus evaluaciones de justicia distributiva siguen una lógica racional. Es decir, existe un discurso racional en donde, si es que no hay algo negativo (i.e injusticia) en la situación de los más desfavorecidos, entonces no hay una razón por la cual se deban generar cambios y por ende, se ha de mantener el _status quo_, incluso si eso implica el uso de tácticas represivas.

<div style="text-align: justify">

No obstante, el efecto de las variables de control muestra diferencias interesantes en esta relación. A partir del análisis multivariado, se observó que el efecto de las variables de control cambia de acuerdo con la situación de violencia que se está evaluando. Por un lado, cuando la situación a evaluar corresponde a que carabineros usara la fuerza para desalojar liceos en toma, el efecto del sentido de injusticia del obrero se mantuvo pese a incluir los controles relevantes por literatura. En cambio, cuando la situación a evaluar corresponde a que carabineros repriman marchas pacíficas, el efecto del sentido de injusticia del obrero perdió significancia al incluir el efecto de ideologías autoritarias y de dominancia social. Este hallazgo se puede interpretar tomando en cuenta el criterio de proporcionalidad en la situación de violencia. La proporcionalidad corresponde a una relación entre la violencia que se utiliza para controlar una situación y el potencial daño que ofrece la situación original [@Bufacchi2007; @Wells1970]. Por ejemplo, el protocolo de carabineros vigente señala que el uso de armas semi-letales como escopetas antidisturbios solo se justifica si es que la vida del carabinero está en riesgo [@Fernandez2019]. En el caso de las situaciones estudiadas en este trabajo, que carabineros utilicen tácticas de represión en una marcha pacífica, sugiere una situación de uso excesivo de la fuerza o, dicho de otra forma, desproporcionalidad en el uso de la violencia. 

<div style="text-align: justify">

Tomando en consideración el criterio de proporcionalidad en la situación de violencia, no es sorpresa que el efecto del sentido de injusticia se haya perdido al considerar el efecto de las ideologías autoritarias y de dominancia social. En la literatura empírica, existe evidencia para sostener que individuos con actitudes más autoritarias y/o ideologías más cercanas a la dominancia social, tienden a justificar más el uso excesivo de la fuerza, en contraste, a su uso proporcional o razonable [@Gerber2017b]. Los hallazgos del presente estudio entregan evidencia que va en línea con los resultados de @Gerber2017b: cuando la situación de violencia que se evalúa se puede clasificar como excesiva, la evaluación de justicia en la situación de los más desfavorecidos deja de ser un factor relevante una vez se consideran las características ideológicas de los individuos. En términos sustantivos, la lógica racional que aplican los individuos al justificar la represión policial en función de la situación de justicia de los más desfavorecidos no aplica cuando la situación de violencia puede ser calificada como excesiva. En estos casos, solo son aquellos sujetos más autoritarios o dominantes los que se mantendrían justificando estas situaciones.


### Sentido de Injusticia, Grupos desaventajados y Justificación de la Violencia (H2a y H2b)

<div style="text-align: justify">

A partir de los antecedentes revisados, se propuso que el sentido de injusticia distributiva jugaría un rol moderador en que individuos de grupos desaventajados justificaran más la violencia por el cambio social y menos por el control social. Esta idea fue puesta a prueba a partir de las hipótesis H2a y H2b, tomando como pertenencia a grupos desaventajados individuos con las siguientes características: ser mujer, tener bajos ingresos, estar insatisfecho con los ingresos, pertenecer al pueblo Mapuche y tener bajo nivel educacional. Los resultados mostraron efectos contrarios a los esperados para el caso de las mujeres, la insatisfacción con los ingresos y los ingresos bajos. 

<div style="text-align: justify">

En el caso de la hipótesis H2a, se esperaba que mujeres e individuos insatisfechos con sus ingresos justificarán más la violencia por el cambio social a medida que evaluarán más injusticia. No obstante, se encontró que las mujeres justificaban menos la violencia que los hombres, diferencia que se acrecentaba a medida que se evaluaba más injusticia. Así también, se encontró que quienes se sentían totalmente insatisfechos con sus ingresos justificaban más la violencia que quienes se sentían totalmente satisfechos, pero esta diferencia se atenúa a medida que se evaluaba más injusticia. A fin de interpretar estos efectos contrarios se ofrece una explicación, a este punto especulativa, la cual podría ser abordada en estudios futuros.

<div style="text-align: justify">

La explicación que se puede entregar para estos efectos contrarios es que las características puestas a prueba (i.e. sexo y satisfacción con los ingresos) no necesariamente representan la pertenencia a grupos desaventajados, por lo que no seguirían la tendencia que se esperaría según el razonamiento en base a la literatura previa [@Runciman1966; @Gurr1970; @BarringtonMoore1978]. Es decir, el comportamiento de las mujeres o de quienes se sienten insatisfechos con sus ingresos podría ser distinto del que se esperaría de alguien perteneciente a un grupo desaventajado, porque refieren a otro tipo de desventaja a la que hasta ahora ha estudiado o no caben dentro de esta categoría. Por ejemplo, en el caso de las mujeres, la literatura previa ha mostrado que estas tienden a justificar menos la violencia que los hombres, independiente de cuál sea el propósito, ya que los hombres suelen tener más disposición a actitudes agresivas y/o violentas [@Gerber2017]. Considerando este antecedente, el resultado de este estudio se comprende mejor si pone como foco de análisis a los hombres: los hombres suelen justificar más la violencia por el cambio social que las mujeres a medida que evalúan más injusticia distributiva. En el caso de la insatisfacción con los ingresos, la interpretación es similar. Esta característica podría no ser representativa de lo que, en la literatura sobre justificación de la violencia se puede englobar como pertenencia a grupos desaventajados, por lo que los efectos podrían no seguir la lógica planteada. Futuros estudios pueden abordar este efecto, determinando si los hallazgos corresponden, efectivamente, a una diferencia en el razonamiento teórico y el uso de indicadores o si existen razones sustantivas por las que los efectos podrían variar.

<div style="text-align: justify">

En el caso de la hipótesis H2b, se esperaba que a medida que disminuyeran los ingresos de los entrevistados, menos se justificaría la violencia por el control social (i.e. desalojo de liceos en toma), relación que se vería acrecentada a medida que aumentaran las evaluaciones de injusticia. No obstante, se encontró que las evaluaciones de injusticia atenúan esta relación. Este hallazgo se puede explicar, especulativamente hasta este punto, considerando la poca coincidencia de los actores insertos en los indicadores. Sustantivamente, el indicador del sentido de injusticia para los obreros representa que tan injusta se considera que es la distribución de ingresos de los obreros. En cambio, el indicador de violencia por el control social representa qué tanto se justifica que carabineros desaloje tomas estudiantiles a la fuerza. Si se toman en consideración a los actores en cada situación, tiene lógica que un individuo de bajos ingresos que evalúa alta injusticia en la situación de los obreros no necesariamente apoya una toma estudiantil, ya que no hay una identificación asegurada entre obreros y estudiantes. Esto se sustenta en los hallazgos en la agenda que plantean que las justificaciones de violencia de ciertos individuos se ven mediadas por la identificación con su grupo [@Gerber2017a; @Gerber2021]. Por ende, se podría proponer que si la situación de violencia si permitiera una identificación entre grupos (e.g. que la situación de violencia favorece o no a obreros), el sentido de injusticia podría seguir el rol esperado. Estudios futuros pueden profundizar y afinar las mediciones, considerando la coincidencia entre actores, y así poder esclarecer estos efectos contrarios


## Limitaciones del estudio

<div style="text-align: justify">

La principal limitante de este estudio se refiere a la medición de las variables, tanto dependientes como independientes. En lo que respecta a la medición de la variable dependiente, la limitante se encuentra en que los indicadores utilizados para medir la justificación de la violencia combinan situaciones de conflicto distintas. En la literatura reciente, se ha propuesto y validado una escala para medir la justificación de la violencia llamada Escala de Apoyo a la Violencia Intergrupal (SVIC, por sus siglas en inglés) [@Gerber2016], la cual cuenta con cuatro indicadores para medir violencia por el cambio social y cuatro para medir la violencia por el cambio social. Los indicadores desarrollados son homogéneos en lo que respecta al tipo de conflicto que se está midiendo, es decir, todos refieren a distintas tácticas de protesta y de represión que se podrían dar en el marco de un conflicto específico, en el caso del trabajo de @Gerber2016, el conflicto Estado-Mapuche. Sin embargo, en el presente estudio se ha utilizado un indicador que se enmarca en el conflicto estudiantil para medir la violencia por el cambio social y dos indicadores para medir la violencia por el control social, donde uno se enmarca en el conflicto estudiantil y otro en ningún conflicto en particular. Esta diferencia conlleva limitantes para las interpretaciones.
 
 <div style="text-align: justify">
 
Las interpretaciones del presente estudio tienen limitaciones respecto a sus alcances. En el caso de los hallazgos sobre la situación en que estudiantes tiren piedras o que carabineros desalojen tomas a la fuerza, las interpretaciones están acotadas al contexto del conflicto estudiantil. Pese a que los indicadores buscan representar un concepto más amplio, la pregunta que se le hace a los entrevistados plantea una situación con elementos característicos del conflicto estudiantil, por ejemplo, que los actores sean estudiantes o que la táctica de protesta sea lanzar piedras. Esto implica que el proceso cognitivo que tienen que hacer los entrevistados al determinar si la situación de violencia se justifica está marcado por estos elementos, así como también por otros que escapan al fraseo de la pregunta, como la historia del conflicto y la relación que tiene el entrevistado con él. En el caso del indicador sobre el uso de la fuerza de carabineros en marchas pacíficas, este no presenta la misma limitante que los otros dos, en tanto no se acota a ninguna situación de conflicto en particular, sin embargo, la limitante en la interpretación en el uso de este indicador es que al no especificar un conflicto en particular, los entrevistados podrían estar pensando en *cualquier marcha pacífica*, lo que dependiendo de sus valores y creencias, podría cambiar radicalmente los hallazgos de la investigación.

<div style="text-align: justify">

 En lo que respecta a la medición de las variables independientes, la limitante se encuentra en que los indicadores utilizados para medir la ideología y la percepción de trato justo no siguen la misma estrategia que los trabajos previos en la literatura. Generalmente, para medir ambos constructos se utilizan técnicas para variables latentes [@Gerber2017b; @Farago2019] las cuales, además de considerar múltiples indicadores, abordan el posible error de medición. Sin embargo, en este trabajo se han utilizado dos indicadores a modo de _proxy_ de la percepción de trato justo y se han elaborado dos índices para medir la ideología autoritaria y la dominancia social. Ambas estrategias asumen que, por un lado, los indicadores escogidos representan la percepción de trato justo y, por otro lado, que los indicadores utilizados para medir la ideología no tienen error de medición. Esto implica que, una medición más precisa de la percepción de trato justo y de las ideologías podrían tener un efecto distinto al utilizarse como controles de las hipótesis que se han puesto a prueba en este estudio.


## Proyecciones de investigación

<div style="text-align: justify">

A partir del presente trabajo, se proponen cuatro proyecciones de investigación que, dados los antecedentes revisados, los hallazgos y las limitaciones del presente estudio, pueden servir de insumo para avanzar en la línea de investigación sobre justicia distributiva y justificación de la violencia. La primera proyección corresponde a estudios que avancen a estudiar el efecto de la injusticia distributiva en la justificación de la violencia de forma longitudinal. Considerando que, a la fecha, los datos de ELSOC cuentan con cinco olas (2016-2021), estudios futuros podrían abordar las hipótesis aquí propuestas e indagar cómo es que los efectos podrían variar (o no) a través del tiempo. Esta propuesta se hace más relevante aún al considerar que los datos analizados en este trabajo corresponden al 2019 y están marcados por un hito particular que es el estallido social, por lo que las relaciones encontradas podrían ser particularmente fuertes por lo reciente de las movilizaciones. En consecuencia, avanzar hacia estudios longitudinales no solo permitiría una mejor comprensión del fenómeno sino también una comprensión más acabada del rol que jugó el contexto del estallido social en que existiera un efecto de la injusticia distributiva en la justificación de la violencia en los resultados de este trabajo.

<div style="text-align: justify">

La segunda proyección corresponde a estudios que avancen a estudiar la relación planteada en este estudio con mejores mediciones y nuevas metodologías. Para esta proyección, se pueden proponer dos líneas a seguir. Por un lado, estudios futuros podrían utilizar las escalas que se han propuesto en la literatura [@Gerber2016] para medir la justificación de la violencia, así como también las estrategias comunes para medir las percepciones de trato justo e ideología [@Gerber2017b; @Farago2019]. Esto permitiría una medición más precisa de los conceptos y, por ende, un estudio más riguroso de las hipótesis aquí planteadas. Por otro lado, estudios futuros podrían avanzar al estudio de la justificación de la violencia a partir del uso de encuestas factoriales. Las encuestas factoriales son una metodología que se utiliza para estudiar el rol que juegan las características de una situación en los juicios subjetivos de esa situación [@Jasso2006]. Considerando que las justificaciones que se hacen de un acto de violencia son situacionales [@Thompson2004], avanzar hacia el estudio de la justificación de la violencia a partir de esta metodología permitiría determinar que características de la situación de violencia son las que influyen en que un acto violento se justifique o no. Por ejemplo, qué tanto influye que quienes sean los que ejercen sean estudiantes o carabineros, o en qué medida influye la forma en la que se ejerce la violencia. En suma, la agenda sobre la justificación de violencia se podría beneficiar del uso de las escalas ya elaboradas, así como también de la implementación de nuevas metodologías como las encuestas factoriales.

<div style="text-align: justify">

La tercera proyección corresponde a estudios que avancen a generar evidencia en torno a qué es lo que las personas consideran violento. En la literatura, la pregunta sobre qué es lo que hace que un acto sea violento ha desencadenado una amplia discusión, la cual se ha resumido en dos propuestas: la definición minimalista y la definición comprehensiva  [@Bufacchi2005]. Pese a estos avances teóricos, en la literatura empírica no se ha generado evidencia sistemática que permita tener un antecedente de qué es lo que ciertas poblaciones consideran violento. Esta carencia de antecedentes implica que, en los estudios sobre la justificación de la violencia, la definición de violencia queda al arbitrio de los investigadores. Considerando que existen antecedentes que plantean que lo que los individuos conciben cómo violento es una determinante de sus justificaciones [@Blumenthal1972], estudios que generen evidencia en torno a las definiciones permitirían avanzar hacia un estudio más riguroso de las justificaciones de la violencia.

<div style="text-align: justify">

La cuarta proyección corresponde a estudios que avancen a estudiar de forma empírica modelos más complejos sobre la violencia. En este estudio se ha indagado en la relación que tendría la injusticia distributiva en la justificación de la violencia (Injusticia → Justificación), tomando como antecedente la literatura que plantea que las acciones violentas se ven determinadas por sus justificaciones (Justificación → Acción), así como también por los antecedentes que proponen que la injusticia distributiva tiene un efecto en la protesta violenta (Injusticia → Acción). Considerando los hallazgos de este trabajo, estudios futuros podrían abordar empíricamente modelos que consideren todos los efectos en conjunto. Por ejemplo, determinar la influencia de la injusticia distributiva en las acciones violentas, tomando en cuenta como esta relación se ve mediada por las justificaciones que hacen los individuos (Injusticia → Justificación → Acción).


## Conclusiones

<div style="text-align: justify">

En síntesis, los resultados de este estudio sientan bases para abrir una nueva línea de investigación entre la justicia distributiva y las justificaciones de la violencia. Si bien el estudio cuenta con limitantes en las formas en las que se han medido los conceptos, se ha generado evidencia que permite plantear, a modo general, que existe un efecto directo en la evaluación de injusticia en los ingresos y la justificación de la violencia. Además, se ha generado evidencia que aporta más específicamente a la literatura, dando cuenta de que quienes justifican la violencia por el cambio social en función de sus evaluaciones de injusticia distributiva, suelen enfocarse en la situación de los más poderosos de la sociedad (e.g. gerentes). En cambio, quienes justifican la violencia por el control social en función de sus evaluaciones de injusticia distributiva, suelen enfocarse en la situación de los más desfavorecidos (e.g. obreros) siguiendo una lógica racional. No obstante, esta lógica solo aplica cuando la violencia que se ejerce en la situación es proporcional o razonable, ya que cuando la violencia se puede calificar de excesiva esta lógica deja de operar y son las características ideológicas de los individuos las que determinan estas situaciones. Considerando estos hallazgos, futuros estudios pueden profundizar esta relación, avanzando hacia 1) estudios longitudinales, 2) estudios que implementen mediciones más precisas o nuevas metodologías, 3) estudios que entreguen un antecedente respecto a las definiciones de la violencia y 4) estudios que incorporen el estudio de la justicia distributiva y la justificación de la violencia en modelos más complejos.