---
title: '¿Quién justifica qué? El rol del sentido de injusticia en las justificaciones de violencia en contexto de protesta'
subtitle: "Tesis para optar al título de Sociólogo"
author: "Martín Venegas Márquez"
date: "`r Sys.Date()`" # o para fecha actual: "`r Sys.Date()`"
institution: "Universidad de Chile"
degree: "Memoria de Título - Carrera de Sociología"
advisor: "Profesor/a guía: Dr. Juan Carlos Castillo"
bibliography: [tesis.bib]
biblio-style: apalike
csl: apa.csl
link-citations: yes
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
fontsize: 14pt
lof: True
lot: True

---

# Resumen {-}

<div style="text-align: justify">

El estudio de las justificaciones de la violencia distingue si esta se ejerce por el cambio social o por el control social. En el marco de esta distinción, emerge la pregunta sobre qué razones o qué características determinan que los individuos justifiquen ambos tipos de violencia. En la literatura empírica se ha encontrado que las justificaciones de ambos tipos de violencia se pueden explicar a partir de la pertenencia a grupos desaventajados, la ideología y las percepciones de justicia procesal. Esta última explicación es la que más ha recibido atención en el último tiempo, sin embargo, en el presente estudio se ha partido de la premisa que la justicia no es un concepto unidimensional, sino uno multidimensional. A raíz de ello, se ha propuesto integrar a la justicia distributiva como una dimensión relevante para explicar las dinámicas de la justificación de la violencia. La pregunta que ha guiado el estudio es: ¿Cuál es la relación entre el sentido de injusticia distributiva y las justificaciones de la violencia en contexto de protesta, tanto por el cambio social, como por el control social, en Chile al año 2019? 

A partir de una muestra de 711 casos de los datos del Estudio Longitudinal Social de Chile (ELSOC) se pusieron a prueba cuatro hipótesis. Por un lado, que quienes evaluarán la distribución de ingresos como más injusta tenderían a justificar más la violencia por el cambio social y menos por el control social. Por otro lado, que individuos que pertenecen a grupos desaventajados justificarían más la violencia por el cambio social y menos por el control social, en la medida que aumentaran sus evaluaciones de injusticia. Para probar las hipótesis se utilizaron modelos de regresión logística ordinal para tres situaciones de violencia: que estudiantes tiren piedras a carabineros, que carabineros repriman marchas pacificas y que carabineros desalojen tomas a la fuerza. Para cada una de estas situaciones, se indagó en el efecto que tenían tres tipos de evaluaciones de injusticia: las evaluaciones que hacen los entrevistados sobre sus ingresos, las evaluaciones para los ingresos de un obrero hipotético y las evaluaciones para los ingresos de un gerente hipotético. 

Los resultados mostraron evidencia para el primer par de hipótesis y evidencia contraria para el segundo par de hipótesis. Para el primer par de hipótesis, se encontró que quienes evalúan más injusticia en los ingresos de los gerentes justifican más la violencia por el cambio social y que quienes evalúan menos injusticia en los ingresos de los obreros justifican más la violencia por el control social. Se discuten las particularidades de cada hallazgo, así como también el rol de los determinantes relevantes según la literatura (e.g. ideología). Para el segundo par de hipótesis, se encontró que las evaluaciones de injusticia tenían un efecto atenuante en que individuos de grupos desaventajados justificarán más la violencia por el cambio social y menos la violencia por el control social. Se abordan estos hallazgos contrarios en las discusiones.


# Abstract {-}

<div style="text-align: justify">

The study of justifications for violence distinguishes whether it is exercised for social change or for social control purposes. Within the framework of this distinction, the question emerges as to what reasons or what characteristics determine that individuals justify both types of violence. The empirical literature has found that justifications for both types of violence can be explained by membership in disadvantaged groups, ideology and perceptions of procedural justice. This last explanation is the one that has received most attention in recent years; however, in the present study I have started from the premise that justice is not a unidimensional concept, but a multidimensional one. As a result, it has been proposed to integrate distributive justice as a relevant dimension to explain the dynamics of the justification of violence. The question that has guided the study is: What is the relationship between the sense of distributive injustice and the justifications of violence in the context of protest, both for social change and social control, in Chile in 2019?

Based on a sample of 711 cases from the Longitudinal Social Study of Chile (ELSOC) data, four hypotheses were tested. On the one hand, that those who would evaluate more injustice in income distribution would tend to justify more violence for social change and less for social control. On the other hand, that individuals belonging to disadvantaged groups would justify violence more by social change and less by social control, as their evaluations of injustice increased. To test the hypotheses, ordinal logistic regression models were used for three situations of violence: students throwing stones at police, police repressing peaceful desmotrations, and police forcibly evicting occupations. For each of these situations, the effect of three types of injustice evaluations were investigated: the interviewees' evaluations of their income, the evaluations for the income of a hypothetical worker, and the evaluations for the income of a hypothetical manager.

Results showed evidence for the first pair of hypotheses and contrary evidence for the second pair of hypotheses. For the first pair of hypotheses, it was found that those who evaluate more managerial income injustice justify more violence for social change and that those who evaluate less worker income injustice justify more violence for social control. The particularities of each finding are discussed, as well as the role of the relevant determinants according to the literature (e.g. ideology). For the second pair of hypotheses, injustice evaluations were found to have a mitigating effect in that individuals from disadvantaged groups will justify more violence for social change and less violence for social control. These contrary findings are addressed in the discussions.


# Agradecimientos {-}

<div style="text-align: justify">

A mediados del año 2020, cuando comenzaba Seminario de Grado, pensaba que la tesis sería simplemente un trabajo más. Sin embargo, con el pasar del tiempo me fui dando cuenta de lo equivocado que estaba. La tesis es una experiencia totalmente distinta a cualquier otro trabajo que se haga durante la U y esto es porque, más que un trabajo, es un ritual de paso. Un ritual con muchos momentos gratificantes, pero sin dejar de ser un proceso largo, solitario y difícil. Es por eso que, el termino de este proceso es un logro que se lo debo a todas las personas que me acompañaron durante él. Me gustaría nombrarlas para expresarles mi gratitud.  

<div style="text-align: justify">

- Le agradezco infinitamente a mis _padres_ Leonor Marquez y Bernardo Venegas. Ellos me dieron todo lo necesario durante la etapa universitaria para poder dedicar gran parte de mi tiempo y energías a estudiar, así también, me comprendieron y apoyaron en los momentos más difíciles.  

<div style="text-align: justify">

- Le agradezco a mi _profesor guía_ Juan Carlos Castillo, no solo por orientarme durante mi proceso, sino también por haberme enseñado gran parte de las cosas que actualmente utilizo para mis labores diarias. También le estoy sumamente agradecido por las instancias de aprendizaje, discusión entre colegas y las oportunidades laborales que me sirvieron para ganar experiencia en el rubro y formarme como profesional.  

<div style="text-align: justify">

- La agradezco a mi _pareja_ Sofía Lovazzano por apoyarme día a día, llenándome la cara de sonrisas cada vez que lo necesitaba y recordándome que la perfección en el trabajo no define el valor como persona.  

<div style="text-align: justify">

- Le agradezco a mis _amigos más cercanos de la U_ Vanessa Leyton, Belén Muñoz, Salvador Urrutia, Jan Dimter, Gabriela Guerra, Diego Esturillo y Andreas Lafferte por esa red de apoyo que siempre estuvo ahí ante cualquier vicisitud. Le agradezco especialmente a Andreas Lafferte por esas discusiones densas sobre teoría y metodología que, a la larga, fueron parte de los pilares de mi trabajo.  

<div style="text-align: justify">

- Le agradezco a mi _colega_ Juan Diego García Castro por abrirme las puertas del mundo de la academia y acompañarme en mis primeros aportes a este mundo. Ha sido un proceso sumamente enriquecedor y uno de los factores que me ayudaron a recobrar la motivación por la sociología. Además, agradezco su comprensión y consejos cuando la tesis parecía una empresa imposible.

<div style="text-align: justify">

- Le agradezco a mi actual _jefatura_ Sebastián Palacios por confiar en mi trabajo desde el principio y no solo darme la oportunidad de hacer mi práctica profesional en la institución que siempre soñé, sino que por abrirme las puertas a trabajar de forma profesional, codo a codo con otros análistas. Esta oportunidad laboral y toda la experiencia que trajo consigo me sirvió para recobrar la motivación por la sociología y darme cuenta que mi trabajo efectivamente tenía un impacto.

<div style="text-align: justify">

A todos las personas mencionadas y, muchas otras más que de forma indirecta me apoyaron, les estoy agradecido por ayudarme a convertirme en lo que soy ahora y lo que seré en el futuro.